{"name": "Create a membership invalid account id. -- @1.3 ", "status": "failed", "statusDetails": {"message": "compare.UnmetExpectation: Expected 400 to equal 404\n", "trace": "  File \"c:\\users\\administrator\\appdata\\local\\programs\\python\\python37\\lib\\site-packages\\behave\\model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"c:\\users\\administrator\\appdata\\local\\programs\\python\\python37\\lib\\site-packages\\behave\\matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"features\\steps\\project_steps.py\", line 41, in step_impl\n    expect(int(status_code)).to_equal(context.response.status_code)\n  File \"c:\\users\\administrator\\appdata\\local\\programs\\python\\python37\\lib\\site-packages\\compare.py\", line 173, in to_equal\n    ensure(self.value == other, True, message)\n  File \"c:\\users\\administrator\\appdata\\local\\programs\\python\\python37\\lib\\site-packages\\compare.py\", line 151, in ensure\n    raise UnmetExpectation(message)\n"}, "steps": [{"name": "Given I set up a \"POST\" request to \"/accounts/{}/memberships\" endpoint", "status": "passed", "start": 1556562164822, "stop": 1556562164824}, {"name": "And I set up the data", "status": "passed", "attachments": [{"name": ".text", "source": "328f5108-7797-4b65-af29-7666190a0c46-attachment.txt", "type": "text/plain"}], "start": 1556562164824, "stop": 1556562164826}, {"name": "When I send the request", "status": "passed", "start": 1556562164827, "stop": 1556562165297}, {"name": "Then I get a \"400\" status code as response", "status": "failed", "statusDetails": {"message": "compare.UnmetExpectation: Expected 400 to equal 404\n", "trace": "  File \"c:\\users\\administrator\\appdata\\local\\programs\\python\\python37\\lib\\site-packages\\behave\\model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"c:\\users\\administrator\\appdata\\local\\programs\\python\\python37\\lib\\site-packages\\behave\\matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"features\\steps\\project_steps.py\", line 41, in step_impl\n    expect(int(status_code)).to_equal(context.response.status_code)\n  File \"c:\\users\\administrator\\appdata\\local\\programs\\python\\python37\\lib\\site-packages\\compare.py\", line 173, in to_equal\n    ensure(self.value == other, True, message)\n  File \"c:\\users\\administrator\\appdata\\local\\programs\\python\\python37\\lib\\site-packages\\compare.py\", line 151, in ensure\n    raise UnmetExpectation(message)\n"}, "start": 1556562165297, "stop": 1556562165301}, {"name": "And I should see a messages error: The path you requested has no valid endpoint.", "status": "skipped", "start": 1556562165302, "stop": 1556562165302}], "parameters": [{"name": "id"}], "start": 1556562163753, "stop": 1556562165302, "uuid": "86cb94b2-3b6c-4f94-ada9-0650ab8f15d1", "historyId": "52e4197d8dc874780490dc6cea05eb33", "labels": [{"name": "tag", "value": "functional_post_negative"}, {"name": "tag", "value": "get_id_first_account"}, {"name": "tag", "value": "account"}, {"name": "severity", "value": "normal"}, {"name": "feature", "value": "Functional test cases Negative to create account membership"}, {"name": "framework", "value": "behave"}, {"name": "language", "value": "cpython3"}]}