{"name": "Get account by id invalid -- @1.3 ", "status": "failed", "statusDetails": {"message": "compare.UnmetExpectation: Expected 400 to equal 404\n", "trace": "  File \"c:\\users\\administrator\\appdata\\local\\programs\\python\\python37\\lib\\site-packages\\behave\\model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"c:\\users\\administrator\\appdata\\local\\programs\\python\\python37\\lib\\site-packages\\behave\\matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"features\\steps\\project_steps.py\", line 42, in step_impl\n    expect(int(status_code)).to_equal(context.response.status_code)\n  File \"c:\\users\\administrator\\appdata\\local\\programs\\python\\python37\\lib\\site-packages\\compare.py\", line 173, in to_equal\n    ensure(self.value == other, True, message)\n  File \"c:\\users\\administrator\\appdata\\local\\programs\\python\\python37\\lib\\site-packages\\compare.py\", line 151, in ensure\n    raise UnmetExpectation(message)\n"}, "steps": [{"name": "Given I set up a \"GET\" request to \"/accounts/{1a2s}\" endpoint", "status": "passed", "start": 1556287310182, "stop": 1556287310183}, {"name": "When I send the request", "status": "passed", "start": 1556287310183, "stop": 1556287310652}, {"name": "Then I get a \"400\" status code as response", "status": "failed", "statusDetails": {"message": "compare.UnmetExpectation: Expected 400 to equal 404\n", "trace": "  File \"c:\\users\\administrator\\appdata\\local\\programs\\python\\python37\\lib\\site-packages\\behave\\model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"c:\\users\\administrator\\appdata\\local\\programs\\python\\python37\\lib\\site-packages\\behave\\matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"features\\steps\\project_steps.py\", line 42, in step_impl\n    expect(int(status_code)).to_equal(context.response.status_code)\n  File \"c:\\users\\administrator\\appdata\\local\\programs\\python\\python37\\lib\\site-packages\\compare.py\", line 173, in to_equal\n    ensure(self.value == other, True, message)\n  File \"c:\\users\\administrator\\appdata\\local\\programs\\python\\python37\\lib\\site-packages\\compare.py\", line 151, in ensure\n    raise UnmetExpectation(message)\n"}, "start": 1556287310652, "stop": 1556287310654}, {"name": "And I should see a messages error: The id isn't valid", "status": "skipped", "start": 1556287310655, "stop": 1556287310655}], "parameters": [{"name": "id", "value": "1a2s"}], "start": 1556287310179, "stop": 1556287310655, "uuid": "c616efc0-3e26-42f4-8017-dca122829ae2", "historyId": "1fba613840f6f37a9f345bde4c788d60", "labels": [{"name": "severity", "value": "normal"}, {"name": "feature", "value": "Get account by id"}, {"name": "framework", "value": "behave"}, {"name": "language", "value": "cpython3"}]}