{"name": "Error try get an account by id of other user account", "status": "passed", "steps": [{"name": "Given I set up a \"GET\" request to \"/accounts/{id}\" endpoint", "status": "passed", "start": 1556562144803, "stop": 1556562144805}, {"name": "When I send the request", "status": "passed", "start": 1556562144805, "stop": 1556562145271}, {"name": "Then I get a \"403\" status code as response", "status": "passed", "start": 1556562145271, "stop": 1556562145273}, {"name": "And I should see a messages error: Authorization failure.", "status": "passed", "start": 1556562145273, "stop": 1556562145274}], "start": 1556562144269, "stop": 1556562145274, "uuid": "a87b40f8-dd9d-43c3-a507-cf814c65dc70", "historyId": "6abdddda41eb6f87cc72f9103dc34179", "labels": [{"name": "tag", "value": "get_id_account_of_other_user"}, {"name": "tag", "value": "functional_get_negative"}, {"name": "tag", "value": "account"}, {"name": "severity", "value": "normal"}, {"name": "feature", "value": "Functional test cases negative of read for account by id"}, {"name": "framework", "value": "behave"}, {"name": "language", "value": "cpython3"}]}