{"name": "Cannot update the \"point scale\" of project strange values -- @1.1 ", "status": "passed", "steps": [{"name": "Given I set up a \"PUT\" request to \"/projects/{proj_id}\" endpoint", "status": "passed", "start": 1556562443571, "stop": 1556562443572}, {"name": "And I set up the data", "status": "passed", "attachments": [{"name": ".text", "source": "8b7a9b3e-5513-4807-a5a7-1327bdfa0d32-attachment.txt", "type": "text/plain"}], "start": 1556562443573, "stop": 1556562443574}, {"name": "When I send the request", "status": "passed", "start": 1556562443575, "stop": 1556562444081}, {"name": "Then I get a \"400\" status code as response", "status": "passed", "start": 1556562444081, "stop": 1556562444082}, {"name": "And I verify the general_problem of error is: \"You can't use negative values for points.\"", "status": "passed", "start": 1556562444083, "stop": 1556562444084}], "parameters": [{"name": "values", "value": "\"-1\""}, {"name": "message", "value": "You can't use negative values for points."}], "start": 1556562443570, "stop": 1556562444084, "uuid": "6c21f51b-1068-4ea4-ab5c-b99a776a99e4", "historyId": "96dad8a7e75880181c2794451af5dd20", "labels": [{"name": "tag", "value": "negative"}, {"name": "tag", "value": "project"}, {"name": "severity", "value": "normal"}, {"name": "feature", "value": "Functional Test Negative Cases of Update Projects"}, {"name": "framework", "value": "behave"}, {"name": "language", "value": "cpython3"}]}