{"name": "Create a membership in account id that doesn't exist. -- @1.1 ", "status": "failed", "statusDetails": {"message": "compare.UnmetExpectation: Expected 'The object you tried to access could not be found.' to be falsy\n", "trace": "  File \"c:\\users\\administrator\\appdata\\local\\programs\\python\\python37\\lib\\site-packages\\behave\\model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"c:\\users\\administrator\\appdata\\local\\programs\\python\\python37\\lib\\site-packages\\behave\\matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"features\\steps\\project_steps.py\", line 239, in step_impl\n    expect(message).to_be_falsy()\n  File \"c:\\users\\administrator\\appdata\\local\\programs\\python\\python37\\lib\\site-packages\\compare.py\", line 390, in to_be_falsy\n    ensure(not bool(self.value), True, message)\n  File \"c:\\users\\administrator\\appdata\\local\\programs\\python\\python37\\lib\\site-packages\\compare.py\", line 151, in ensure\n    raise UnmetExpectation(message)\n"}, "steps": [{"name": "Given I set up a \"POST\" request to \"/accounts/{0}/memberships\" endpoint", "status": "passed", "start": 1556562159764, "stop": 1556562159765}, {"name": "And I set up the data", "status": "passed", "attachments": [{"name": ".text", "source": "8e5341bb-4bb1-4833-be27-bcee019e56d6-attachment.txt", "type": "text/plain"}], "start": 1556562159765, "stop": 1556562159767}, {"name": "When I send the request", "status": "passed", "start": 1556562159767, "stop": 1556562160204}, {"name": "Then I get a \"404\" status code as response", "status": "passed", "start": 1556562160204, "stop": 1556562160208}, {"name": "And I should see a messages error: The object you tried to access could not be found.", "status": "failed", "statusDetails": {"message": "compare.UnmetExpectation: Expected 'The object you tried to access could not be found.' to be falsy\n", "trace": "  File \"c:\\users\\administrator\\appdata\\local\\programs\\python\\python37\\lib\\site-packages\\behave\\model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"c:\\users\\administrator\\appdata\\local\\programs\\python\\python37\\lib\\site-packages\\behave\\matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"features\\steps\\project_steps.py\", line 239, in step_impl\n    expect(message).to_be_falsy()\n  File \"c:\\users\\administrator\\appdata\\local\\programs\\python\\python37\\lib\\site-packages\\compare.py\", line 390, in to_be_falsy\n    ensure(not bool(self.value), True, message)\n  File \"c:\\users\\administrator\\appdata\\local\\programs\\python\\python37\\lib\\site-packages\\compare.py\", line 151, in ensure\n    raise UnmetExpectation(message)\n"}, "start": 1556562160208, "stop": 1556562160214}], "parameters": [{"name": "id", "value": "0"}], "start": 1556562158672, "stop": 1556562160214, "uuid": "67c8ffd3-56dd-451a-8178-693aaa60b0c0", "historyId": "a3fb57f8acb4edcd0e23373e4b089eda", "labels": [{"name": "tag", "value": "get_person_id"}, {"name": "tag", "value": "functional_post_negative"}, {"name": "tag", "value": "account"}, {"name": "severity", "value": "normal"}, {"name": "feature", "value": "Functional test cases Negative to create account membership"}, {"name": "framework", "value": "behave"}, {"name": "language", "value": "cpython3"}]}