{"name": "Cannot update the \"point scale\" of project strange values -- @1.3 ", "status": "passed", "steps": [{"name": "Given I set up a \"PUT\" request to \"/projects/{proj_id}\" endpoint", "status": "passed", "start": 1556562444587, "stop": 1556562444588}, {"name": "And I set up the data", "status": "passed", "attachments": [{"name": ".text", "source": "7152a4dd-0b91-4efa-a813-da75d8942c3b-attachment.txt", "type": "text/plain"}], "start": 1556562444588, "stop": 1556562444589}, {"name": "When I send the request", "status": "passed", "start": 1556562444589, "stop": 1556562445136}, {"name": "Then I get a \"400\" status code as response", "status": "passed", "start": 1556562445136, "stop": 1556562445138}, {"name": "And I verify the general_problem of error is: \"There are too many values in this point scale. Please use 12 or fewer values.\"", "status": "passed", "start": 1556562445139, "stop": 1556562445140}], "parameters": [{"name": "values", "value": "\"100,101,103,104,105,106,107,108,109,110,111,112,113\""}, {"name": "message", "value": "There are too many values in this point scale. Please use 12 or fewer values."}], "start": 1556562444586, "stop": 1556562445140, "uuid": "b9cd74fe-dc9a-41d6-a207-ceee5f7c7f14", "historyId": "82bd5315a30d652a841596a49b6a72f5", "labels": [{"name": "tag", "value": "negative"}, {"name": "tag", "value": "project"}, {"name": "severity", "value": "normal"}, {"name": "feature", "value": "Functional Test Negative Cases of Update Projects"}, {"name": "framework", "value": "behave"}, {"name": "language", "value": "cpython3"}]}