{"name": "Create a membership invalid account id. -- @1.2 ", "status": "failed", "statusDetails": {"message": "compare.UnmetExpectation: Expected 400 to equal 404\n", "trace": "  File \"c:\\users\\administrator\\appdata\\local\\programs\\python\\python37\\lib\\site-packages\\behave\\model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"c:\\users\\administrator\\appdata\\local\\programs\\python\\python37\\lib\\site-packages\\behave\\matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"features\\steps\\project_steps.py\", line 41, in step_impl\n    expect(int(status_code)).to_equal(context.response.status_code)\n  File \"c:\\users\\administrator\\appdata\\local\\programs\\python\\python37\\lib\\site-packages\\compare.py\", line 173, in to_equal\n    ensure(self.value == other, True, message)\n  File \"c:\\users\\administrator\\appdata\\local\\programs\\python\\python37\\lib\\site-packages\\compare.py\", line 151, in ensure\n    raise UnmetExpectation(message)\n"}, "steps": [{"name": "Given I set up a \"POST\" request to \"/accounts/{23.4}/memberships\" endpoint", "status": "passed", "start": 1556562163187, "stop": 1556562163188}, {"name": "And I set up the data", "status": "passed", "attachments": [{"name": ".text", "source": "63c2e79f-de9c-4fde-9889-6e5a6d6917e6-attachment.txt", "type": "text/plain"}], "start": 1556562163188, "stop": 1556562163190}, {"name": "When I send the request", "status": "passed", "start": 1556562163190, "stop": 1556562163644}, {"name": "Then I get a \"400\" status code as response", "status": "failed", "statusDetails": {"message": "compare.UnmetExpectation: Expected 400 to equal 404\n", "trace": "  File \"c:\\users\\administrator\\appdata\\local\\programs\\python\\python37\\lib\\site-packages\\behave\\model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"c:\\users\\administrator\\appdata\\local\\programs\\python\\python37\\lib\\site-packages\\behave\\matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"features\\steps\\project_steps.py\", line 41, in step_impl\n    expect(int(status_code)).to_equal(context.response.status_code)\n  File \"c:\\users\\administrator\\appdata\\local\\programs\\python\\python37\\lib\\site-packages\\compare.py\", line 173, in to_equal\n    ensure(self.value == other, True, message)\n  File \"c:\\users\\administrator\\appdata\\local\\programs\\python\\python37\\lib\\site-packages\\compare.py\", line 151, in ensure\n    raise UnmetExpectation(message)\n"}, "start": 1556562163644, "stop": 1556562163651}, {"name": "And I should see a messages error: The path you requested has no valid endpoint.", "status": "skipped", "start": 1556562163652, "stop": 1556562163652}], "parameters": [{"name": "id", "value": "23.4"}], "start": 1556562161935, "stop": 1556562163652, "uuid": "08835035-a700-47cb-80a5-775b7e513ee9", "historyId": "60038a85f525709acae697b2d95b8172", "labels": [{"name": "tag", "value": "functional_post_negative"}, {"name": "tag", "value": "get_id_first_account"}, {"name": "tag", "value": "account"}, {"name": "severity", "value": "normal"}, {"name": "feature", "value": "Functional test cases Negative to create account membership"}, {"name": "framework", "value": "behave"}, {"name": "language", "value": "cpython3"}]}