{"name": "Cannot update the integer param of \"number_of_done_iterations_to_show\" of project with extreme values -- @1.1 ", "status": "passed", "steps": [{"name": "Given I set up a \"PUT\" request to \"/projects/{proj_id}\" endpoint", "status": "passed", "start": 1556562459573, "stop": 1556562459573}, {"name": "And I set up the data", "status": "passed", "attachments": [{"name": ".text", "source": "a7df037f-bf96-4cc9-9f8d-bcdc14fba7e4-attachment.txt", "type": "text/plain"}], "start": 1556562459574, "stop": 1556562459576}, {"name": "When I send the request", "status": "passed", "start": 1556562459577, "stop": 1556562460112}, {"name": "Then I get a \"400\" status code as response", "status": "passed", "start": 1556562460113, "stop": 1556562460114}, {"name": "And I verify the general_problem of error is: \"Your project must load enough done iterations to calculate your velocity according to your settings.\"", "status": "passed", "start": 1556562460115, "stop": 1556562460116}], "parameters": [{"name": "number", "value": "1"}, {"name": "message", "value": "Your project must load enough done iterations to calculate your velocity according to your settings."}], "start": 1556562459571, "stop": 1556562460116, "uuid": "d353f9f8-c234-4c3b-a587-98a989d1cb70", "historyId": "c10180d776f764cc5954d423e31e5400", "labels": [{"name": "tag", "value": "negative"}, {"name": "tag", "value": "project"}, {"name": "severity", "value": "normal"}, {"name": "feature", "value": "Functional Test Negative Cases of Update Projects"}, {"name": "framework", "value": "behave"}, {"name": "language", "value": "cpython3"}]}